
<?php require 'templates/layout/header.phtml' ?>
    <div class="container mt-5">
        <h2 class="text-center">Iniciar Sesión</h2>

        <?php if ($error): ?>
        <div class='alert alert-danger' role='alert'>
            <?= $error ?>
        </div>
        <?php endif ?>

        <form method='post' action='login' class="mt-4">
            <div class='form-group'>
                <label for='Nombre'>Nombre</label>
                <input type='text' class='form-control' id='name' name='name' required>
            </div>
            <div class='form-group mt-3'>
                <label for='password'>Contraseña</label>
                <input type='password' class='form-control' id='password' name='password' required>
            </div>
            <button type='submit' class='btn btn-primary mt-4'>Iniciar Sesión</button>
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>

