<?php require 'templates/layout/header.phtml' ?>

    <div class="container mt-5">
        <h1 class="text-center mb-4">Detalle de Libro</h1>
        
        <div class="card">
            <div class="card-body">
                <p><strong>Título:</strong> <?= htmlspecialchars($libro->Titulo, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Autor:</strong> <?= htmlspecialchars($libro->Autor, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Precio:</strong> $ <?= htmlspecialchars($libro->Precio, ENT_QUOTES, 'UTF-8') ?> </p>
                <p><strong>Genero:</strong> <?= htmlspecialchars($libro->Genero, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Editorial:</strong> <?= htmlspecialchars($libro->Editorial, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Pedido N° :</strong> <?= htmlspecialchars($libro->id_compra, ENT_QUOTES, 'UTF-8') ?></p>
                
                <div class="mt-4">
                    <a href="<?= BASE_URL ?>editarLibro/<?= htmlspecialchars($libro->ID_Libro, ENT_QUOTES, 'UTF-8') ?>" class="btn btn-warning">Editar</a>
                    <?php if ($libro->id_compra != NULL): ?>
                        <h3>Este Libro tiene un pedido</h3>
                    <?php else: ?>
                        <a href="<?= BASE_URL ?>eliminarLibro/<?= htmlspecialchars($libro->ID_Libro, ENT_QUOTES, 'UTF-8') ?>/" class="btn btn-danger">Eliminar</a>
                    <?php endif; ?>
                    <a href="<?= BASE_URL ?>libros" class="btn btn-secondary">Volver</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>
