<?php require 'templates/layout/header.phtml' ?>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="mb-4">Editar Género</h1>
                <form method="POST" class="border p-4 rounded">
                    <div class="mb-3">
                        <label for="genero" class="form-label">Nombre del Género:</label>
                        <input type="text" name="genero" id="genero" class="form-control" value="<?= htmlspecialchars($genero, ENT_QUOTES, 'UTF-8') ?>" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Cambiar</button>
                </form>
                <a href="<?= BASE_URL ?>listarCategorias" class="btn btn-secondary mt-3">Volver</a>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>

