<?php require 'templates/layout/header.phtml' ?>

    <div class="container-porCategoria mt-5">
    <h1 class="text-center text-secondary">Libros del género: <span class="text-uppercase"><?= $genero ?></span></h1>
    
    <div class="d-flex justify-content-center">
        <ul class="list-group list-group-flush mt-4" style="max-width: 900px;">
            <?php foreach($libros as $libro) : ?>
                <li class="list-group-item d-flex justify-content-between align-items-center border-0">
                    <div class="w-100 d-flex justify-content-between align-items-center">
                        <div>
                            <a href="<?= BASE_URL ?>detallarLibro/<?= $libro->ID_Libro ?>" class="text-decoration-none text-dark fw-bold">
                                <?= $libro->Titulo ?>
                            </a>
                            <small class="d-block text-muted"><?= $libro->Autor ?></small>
                        </div>
                        <span class="text-muted ms-3">$<?= $libro->Precio ?></span>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="text-center mt-4">
        <a href="<?= BASE_URL ?>listarCategorias" class="btn btn-outline-secondary">Volver a Categorías</a>
    </div>
</div>


    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>