<?php require './templates/layout/header.phtml'; ?>

<div class="container mt-5">
    <h1 class="mb-4 text-center">Crear Pedido</h1>
    <form action="<?= BASE_URL ?>crearPedido" method="POST" class="mb-5">
        <div class="mb-3">
            <label for="local" class="form-label">Local:</label>
            <input type="text" id="local" name="local" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="id_cliente" class="form-label">ID Cliente:</label>
            <input type="number" id="id_cliente" name="id_cliente" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="precio" class="form-label">Total:</label>
            <input type="number" id="precio" name="precio" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Crear Pedido</button>
    </form>

    <h1 class="mb-4 text-center">Lista de Pedidos</h1>
    <div class="row">
        <?php foreach ($pedidos as $c): ?>
        <div class="col-md-4">
            <div class="card mb-4">
                <div class="card-body">
                    <h5 class="card-title">Compra ID: <?= $c->ID_Compra ?></h5>
                    <p class="card-text">Fecha: <?= $c->Fecha_compra ?></p>
                    <p class="card-text">Total: $<?= number_format($c->Total, 2) ?></p>
                    <p class="card-text">Local: <?= $c->Local ?></p>
                    <p class="card-text">ID Cliente: <?= $c->ID_Cliente ?></p>
                    <a href="detallarPedido/<?=$c->ID_Compra ?>/" class="btn btn-success">Ver pedido</a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
