<?php require 'templates/layout/header.phtml' ?>

    <div class="container mt-5">
        <h1 class="text-center mb-4">Detalle de Pedido</h1>
        
        <div class="card">
            <div class="card-body">
                <p><strong>N° Pedido: </strong> <?= htmlspecialchars($pedido->ID_Compra, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Fecha de compra: </strong> <?= htmlspecialchars($pedido->Fecha_compra, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>Total: </strong> $ <?= htmlspecialchars($pedido->Total, ENT_QUOTES, 'UTF-8') ?> </p>
                <p><strong>Local: </strong> <?= htmlspecialchars($pedido->Local, ENT_QUOTES, 'UTF-8') ?></p>
                <p><strong>ID_Cliente:</strong> <?= htmlspecialchars($pedido->ID_Cliente, ENT_QUOTES, 'UTF-8') ?></p>
                
                <div class="mt-4">
                    <a href="<?= BASE_URL ?>editarPedido/<?= htmlspecialchars($pedido->ID_Compra, ENT_QUOTES, 'UTF-8') ?>" class="btn btn-warning">Editar</a>
                    <a href="<?= BASE_URL ?>eliminarPedido/<?= htmlspecialchars($pedido->ID_Compra, ENT_QUOTES, 'UTF-8') ?>/" class="btn btn-danger">Eliminar</a>
                    <a href="<?= BASE_URL ?>pedidos" class="btn btn-secondary">Volver</a>
                </div>

                <div class="container-lista-libros">
                    <div class="row">
                        <?php foreach ($libros as $l): ?>
                        <div class="card" style="width: 18rem; margin: 10px;">
                            <div class="card-body">
                                <h5 class="card-title"><?= htmlspecialchars($l->Titulo, ENT_QUOTES, 'UTF-8')?></h5>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
    </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>