<?php require 'templates/layout/header.phtml' ?>

    <div class="container mt-5">
        <h1 class="text-center mb-4">Editar Pedido</h1>
        <form method="POST" action="<?= BASE_URL ?>editarPedido/<?= htmlspecialchars($pedido->ID_Compra, ENT_QUOTES, 'UTF-8') ?>">

            <div class="mb-3">
                <label for="titulo" class="form-label">Total:</label>
                <input type="text" name="Total" id="Total" class="form-control" value="<?= htmlspecialchars($pedido->Total, ENT_QUOTES, 'UTF-8') ?>" required>
            </div>

            <div class="mb-3">
                <label for="autor" class="form-label">Local:</label>
                <input type="text" name="Local" id="Local" class="form-control" value="<?= htmlspecialchars($pedido->Local, ENT_QUOTES, 'UTF-8') ?>" required>
            </div>
            <button type="submit" class="btn btn-primary">Cambiar</button>
        </form>
        <div class="text-center mt-3">
            <a href="<?= BASE_URL ?>pedidos" class="btn btn-secondary">Volver</a>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>