<?php require 'templates/layout/header.phtml' ?>

    <div class="container mt-5">
        <h1 class="text-center mb-4">Editar Libro</h1>
        <form method="POST" action="<?= BASE_URL ?>editarLibro/<?= htmlspecialchars($libro->ID_Libro, ENT_QUOTES, 'UTF-8') ?>">

            <div class="mb-3">
                <label for="titulo" class="form-label">Título:</label>
                <input type="text" name="titulo" id="titulo" class="form-control" value="<?= htmlspecialchars($libro->Titulo, ENT_QUOTES, 'UTF-8') ?>" required>
            </div>

            <div class="mb-3">
                <label for="autor" class="form-label">Autor:</label>
                <input type="text" name="autor" id="autor" class="form-control" value="<?= htmlspecialchars($libro->Autor, ENT_QUOTES, 'UTF-8') ?>" required>
            </div>

            <div class="mb-3">
                <label for="precio" class="form-label">Precio:</label>
                <input type="number" name="precio" id="precio" class="form-control" value="<?= htmlspecialchars($libro->Precio, ENT_QUOTES, 'UTF-8') ?>" required>
            </div>

            <div class="mb-3">
                <label for="genero" class="form-label">Editorial:</label>
                <input type="text" name="editorial" id="editorial" class="form-control"  value="<?= htmlspecialchars($libro->Editorial, ENT_QUOTES, 'UTF-8') ?>"  required>
            </div>

            <div class="mb-3">
                <label for="genero" class="form-label">Género:</label>
                <input type="text" name="genero" id="genero" class="form-control"  value="<?= htmlspecialchars($libro->Genero, ENT_QUOTES, 'UTF-8') ?>" required>
            </div>

            <select name="pedido" id="pedido" class="form-select" required>
                <?php foreach ($pedidos as $pedido): ?>
                    <option value="<?=$pedido->ID_Compra ?>"> <?=$pedido->ID_Compra ?></option>
                 <?php endforeach;?>
            </select>
            
            <button type="submit" class="btn btn-primary">Cambiar</button>
        </form>
        <div class="text-center mt-3">
            <a href="<?= BASE_URL ?>libros" class="btn btn-secondary">Volver</a>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>

