<?php require 'templates/layout/header.phtml' ?>

    <div class="container-lista-libros">
        <div class="row">
            <?php foreach ($libro as $l): ?>
            <div class="card" style="width: 18rem; margin: 10px;">
                <div class="card-body">
                    <h5 class="card-title"><?= $l->Titulo ?></h5>
                    <p class="card-text">Categoría: <?= $l->Genero ?></p>
                    <a href="detallarLibro/<?=$l->ID_Libro ?>/" class="btn btn-primary">Ver detalles</a>
                </div>
            </div>
            <?php endforeach; ?>
        </div>

        <a href="<?= BASE_URL ?>crearLibro" class="btn btn-success">CREAR LIBRO</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>

