<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Librería</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="<?= BASE_URL ?>libros">Libreria</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>libros">Libros</a>
                <a class="nav-link" href="<?= BASE_URL ?>listarCategorias">Géneros</a>
                <a class="nav-link" href="<?= BASE_URL ?>pedidos">Pedidos</a>

                <!-- Verificar si el usuario está autenticado -->
                <?php if (isset($_SESSION['ID_USER'])): ?>
                    <!-- Mostrar 'Cerrar sesión' cuando el usuario está logueado -->
                    <a class="nav-link" href="<?= BASE_URL ?>logout">Cerrar sesión (<?php echo htmlspecialchars($_SESSION['NAME_USER']); ?>)</a>
                <?php else: ?>
                    <!-- Mostrar 'Iniciar sesión' cuando el usuario no está logueado -->
                    <a class="nav-link" href="<?= BASE_URL ?>showLogin">Iniciar sesión</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</nav>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
</body>

</html>
